### ISSUE TITLE
Channel with ID ‘deviceActive’ does not exists

### ISSUE THREAD

**Issue by cauer71** [astenlund74/org.openhab.binding.spotify-binary#1]
21:49:13.240 [INFO ] [smarthome.event.ThingUpdatedEvent ] - Thing ‘spotify:player:0fb2bb1c’ has been updated.
21:49:13.314 [INFO ] [marthome.event.ConfigStatusInfoEvent] - ConfigStatusInfo [configStatusMessages=[]]
21:49:14.130 [INFO ] [marthome.event.ConfigStatusInfoEvent] - ConfigStatusInfo [configStatusMessages=[]]
21:49:15.086 [INFO ] [marthome.event.ItemStateChangedEvent] - spotify_player_user1_trackRepeat changed from NULL to off
21:49:15.088 [INFO ] [marthome.event.ItemStateChangedEvent] - spotify_player_user1_trackProgress changed from NULL to 5:10
21:49:15.095 [INFO ] [marthome.event.ItemStateChangedEvent] - spotify_player_user1_trackDuration changed from NULL to 5:17
21:49:15.099 [INFO ] [marthome.event.ItemStateChangedEvent] - spotify_player_user1_trackName changed from NULL to The Girl From Ipanema
21:49:15.104 [INFO ] [marthome.event.ItemStateChangedEvent] - spotify_player_user1_albumName changed from NULL to Stan Getz: The Bossa Nova Albums
**21:49:15.103 [ERROR] [nding.spotify.handler.SpotifyHandler] - Exception caught in anonymous scheduled runnable task. This task will now stop.**
java.lang.IllegalArgumentException: Channel with ID ‘deviceActive’ does not exists.
at org.eclipse.smarthome.core.thing.binding.BaseThingHandler.isLinked(BaseThingHandler.java:573)[105:org.eclipse.smarthome.core.thing:0.9.0.b5]
at org.openhab.binding.spotify.handler.SpotifyHandler.setChannelValue(SpotifyHandler.java:423)[224:org.openhab.binding.spotify:2.1.0.201709070932]
at org.openhab.binding.spotify.handler.SpotifyHandler.updatePlayerInfo(SpotifyHandler.java:410)[224:org.openhab.binding.spotify:2.1.0.201709070932]
at org.openhab.binding.spotify.handler.SpotifyHandler.lambda$0(SpotifyHandler.java:272)[224:org.openhab.binding.spotify:2.1.0.201709070932]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)[:1.8.0_121]
at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)[:1.8.0_121]
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)[:1.8.0_121]
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)[:1.8.0_121]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)[:1.8.0_121]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)[:1.8.0_121]
at java.lang.Thread.run(Thread.java:745)[:1.8.0_121]
21:49:15.118 [INFO ] [marthome.event.ItemStateChangedEvent] - spotify_player_user1_artistName changed from NULL to Stan Getz

**Comment by cauer71** [comment]
the binding crashes with this error

**Comment by astenlund74** [comment]
@cauer71 thanks for reporting the issue. I do think that issue has already been resolved in the pull request source branch. I have added an updated binary which is updated for 2.2.0 release of openHAB. Please try that one and see if it works better for you.

**Comment by cauer71** [comment]
now it works fine, thx
